services:

  archi2csv:
    build:
      context: https://github.com/MaksimAniskov/archi-powertools-verifier.git#1.x:/archixml2csv
    environment:
      ARCHI_FILE:
      ARCHI_FILE2:
      MODELS_FOLDER: /usr/var/archimate_models
    working_dir: /usr/var/intermediate_files
    volumes:
      - ${ARCHI_FOLDER-.}:/usr/var/archimate_models:ro
      - intermediate_files:/usr/var/intermediate_files

  neo4j:
    depends_on:
      archi2csv:
        condition: service_completed_successfully
    build:
      context: https://github.com/MaksimAniskov/archi-powertools-verifier.git#1.x:/neo4j
    volumes:
      - intermediate_files:/var/lib/neo4j/import/intermediate_files
      - ${NEO4J_SCRIPTS_FOLDER-./verification_scripts_cql}:/usr/var/verification_scripts:ro
      - ${ADDITIONAL_DATA_FOLDER-./additional_data}:/usr/var/additional_data:ro

  sqlite:
    depends_on:
      archi2csv:
        condition: service_completed_successfully
    build:
      context: https://github.com/MaksimAniskov/archi-powertools-verifier.git#1.x:/sqlite
    volumes:
      - intermediate_files:/usr/var/intermediate_files
      - ${SQLITE_SCRIPTS_FOLDER-./verification_scripts_sql}:/usr/var/verification_scripts:ro
      - ${ADDITIONAL_DATA_FOLDER-./additional_data}:/usr/var/additional_data:ro

volumes:
  intermediate_files: {}