services:

  archi2csv:
    build:
      context: https://github.com/MaksimAniskov/archi-powertools-verifier.git#main:/archixml2csv
    command: python /usr/src/archixml2csv.py /usr/var/archimate_models/"${INPUT_ARCHI_FILE-model.archimate}"
    working_dir: /usr/var/intermediate_files
    volumes:
      - ${INPUT_ARCHI_FOLDER-.}:/usr/var/archimate_models:ro
      - intermediate_files:/usr/var/intermediate_files

  neo4j:
    depends_on:
      archi2csv:
        condition: service_completed_successfully
    build:
      context: https://github.com/MaksimAniskov/archi-powertools-verifier.git#main:/neo4j
    volumes:
      - intermediate_files:/var/lib/neo4j/import/intermediate_files
      - ${INPUT_NEO4J_SCRIPTS_FOLDER-./verification_scripts}:/usr/var/verification_scripts:ro

volumes:
  intermediate_files: {}