services:

  archi:
    build:
      context: https://github.com/MaksimAniskov/archi-powertools-verifier.git#1.x:/archi
    platform: linux/amd64
    environment:
      GIT_URL:
      GIT_USER:
      GIT_PASSWORD_FILE:
      GIT_URL2:
      GIT_USER2:
      GIT_PASSWORD_FILE2:
    volumes:
      - ${GIT_PASSWORD_FILES_FOLDER-.}:/usr/var/passwords:ro
      - intermediate_files:/usr/var/intermediate_files

  archi2csv:
    depends_on:
      archi:
        condition: service_completed_successfully
    environment:
      MODELS_FOLDER: /usr/var/intermediate_files
      ARCHI_FILE2: model2.archimate
    volumes:
      - intermediate_files:/usr/var/intermediate_files
